name: 同步微信公众号文章

on:
  workflow_dispatch:
    inputs:
      article_url:
        description: '微信文章URL'
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 安装依赖
        run: |
          npm install puppeteer cheerio moment slugify
          npx puppeteer browsers install chrome

      - name: 创建目录
        run: |
          mkdir -p docs/blog/wechat
      
      - name: 抓取微信文章
        run: node scripts/fetch-wechat.js "${{ github.event.inputs.article_url }}"
      
      - name: 提交到仓库
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/blog/wechat/
          git commit -m "同步微信公众号文章: ${{ github.event.inputs.article_url }}"
          git push https://x-access-token:${{ secrets.PRIVATE_GITHUB_ACTION }}@github.com/wang-fu/blog.git HEAD:master

      - name: 触发构建部署
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PRIVATE_GITHUB_ACTION }}" \
            https://api.github.com/repos/wang-fu/blog/actions/workflows/blank.yml/dispatches \
            -d '{"ref":"master"}' 